services:
  telegram_bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      INFO_SPREADSHEET_KEY: ${INFO_SPREADSHEET_KEY}
      ACC_SPREADSHEET_KEY: ${ACC_SPREADSHEET_KEY}
    restart: always
